#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

if output=$(curl http://$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT 2>&1)
then
  client_result "Application is running"
else
  client_result "Application is either stopped or inaccessible"
fi
